In [1]:
import tensorflow as tf

tf.__version__

'2.16.1'

In [12]:
# Initialization of tensors
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

y = tf.ones((3, 3))
print(y)

z = tf.zeros((2, 3))
print(z)

a = tf.eye(3) # I for identity matrix
print(a)

k = tf.random.normal((3, 3), mean=0, stddev=1)
print(k)

l = tf.random.uniform((1, 3), minval=0, maxval=1)
print(l)

j = tf.range(9)
print(j)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.34655446  0.18198532 -1.1332387 ]
 [ 1.0350839   1.2850142  -1.0044308 ]
 [ 0.36735293  1.2168483  -0.8355212 ]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.13754487 0.50657    0.3146875 ]], shape=(1, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [13]:
# Mathematical operations
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [19]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[:3])
print(x[1:3])
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [20]:
# Reshaping
x = tf.range(9)
x = tf.reshape(x, (3, 3))
x= tf.transpose(x)
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
